import type {
  ArtifactIndex,
  EvaluationEntity,
  FinalRobustnessBundle,
  FinalRobustnessReportData,
  FinalRobustnessReportSummary,
  ReportEntity,
  RunEntity,
} from "@/lib/manifest/types";

const FINAL_REPORT: ReportEntity = {
  id: "phase26_report",
  entity_type: "report",
  report_scope: "phase26_robustness_final",
  default_visible: true,
  is_official: true,
  artifact_refs: {
    report_markdown: { path: "artifacts/reports/phase26/report.md", exists: true },
    report_data_json: { path: "artifacts/reports/phase26/report_data.json", exists: true },
    report_summary_json: { path: "artifacts/reports/phase26/report_summary.json", exists: true },
    worst_group_summary_csv: { path: "artifacts/reports/phase26/worst_group.csv", exists: true },
    ood_summary_csv: { path: "artifacts/reports/phase26/ood.csv", exists: true },
    id_summary_csv: { path: "artifacts/reports/phase26/id.csv", exists: true },
    calibration_summary_csv: { path: "artifacts/reports/phase26/calibration.csv", exists: true },
  },
  payload_refs: {
    report_data_json: { path: "artifacts/reports/phase26/report_data.json", exists: true },
    report_summary_json: { path: "artifacts/reports/phase26/report_summary.json", exists: true },
  },
};

const TEMPERATURE_REPORT: ReportEntity = {
  id: "phase18_report",
  entity_type: "report",
  report_scope: "phase18_temperature_scaling_seeded",
  default_visible: true,
  is_official: true,
  artifact_refs: {
    report_markdown: { path: "artifacts/reports/phase18/report.md", exists: true },
    report_data_json: { path: "artifacts/reports/phase18/report_data.json", exists: true },
    mitigation_comparison_table_csv: {
      path: "artifacts/reports/phase18/mitigation_table.csv",
      exists: true,
    },
  },
};

const REWEIGHTING_REPORT: ReportEntity = {
  id: "phase19_report",
  entity_type: "report",
  report_scope: "phase19_reweighting_seeded",
  default_visible: true,
  is_official: true,
  artifact_refs: {
    report_markdown: { path: "artifacts/reports/phase19/report.md", exists: true },
    report_data_json: { path: "artifacts/reports/phase19/report_data.json", exists: true },
    mitigation_comparison_table_csv: {
      path: "artifacts/reports/phase19/mitigation_table.csv",
      exists: true,
    },
  },
};

const FINAL_REPORT_DATA: FinalRobustnessReportData = {
  official_method_summaries: [
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Temperature Scaling",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "temperature_scaling",
      metrics: {
        mean: {
          worst_group_f1: 0,
          ood_macro_f1: 0,
          id_macro_f1: 0,
          ece: -0.011,
          brier_score: -0.001,
        },
        std: {
          worst_group_f1: 0,
          ood_macro_f1: 0,
          id_macro_f1: 0,
          ece: 0.001,
          brier_score: 0.0001,
        },
      },
      primary_verdict: "stable",
      seed_count: 3,
      seeded_interpretation: "stable",
      stability_label: "stable",
      story_note: "Stable calibration reference lane with no meaningful robustness upside.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Reweighting",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "reweighting",
      metrics: {
        mean: {
          worst_group_f1: 0.06,
          ood_macro_f1: 0.001,
          id_macro_f1: -0.011,
          ece: 0.006,
          brier_score: 0.007,
        },
        std: {
          worst_group_f1: 0.008,
          ood_macro_f1: 0.001,
          id_macro_f1: 0.002,
          ece: 0.001,
          brier_score: 0.001,
        },
      },
      primary_verdict: "mixed",
      seed_count: 3,
      seeded_interpretation: "stable",
      stability_label: "mixed",
      story_note: "Best current robustness lane, but the official seeded story remains mixed.",
    },
  ],
  exploratory_method_summaries: [
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Group DRO",
      evidence_scope: "exploratory_scout",
      is_exploratory: true,
      method_name: "group_dro",
      metrics: {
        mean: {
          worst_group_f1: -0.215,
          ood_macro_f1: -0.037,
          id_macro_f1: -0.086,
          ece: 0.033,
          brier_score: 0.026,
        },
        std: {
          worst_group_f1: null,
          ood_macro_f1: null,
          id_macro_f1: null,
          ece: null,
          brier_score: null,
        },
      },
      primary_verdict: "failure",
      promotion_decision: "do_not_promote",
      seed_count: 1,
      story_note: "Scout failure against the parent baseline; not worth promotion.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Group-Balanced Sampling",
      evidence_scope: "exploratory_scout",
      is_exploratory: true,
      method_name: "group_balanced_sampling",
      metrics: {
        mean: {
          worst_group_f1: 0.153,
          ood_macro_f1: -0.096,
          id_macro_f1: -0.118,
          ece: 0.116,
          brier_score: 0.092,
        },
        std: {
          worst_group_f1: null,
          ood_macro_f1: null,
          id_macro_f1: null,
          ece: null,
          brier_score: null,
        },
      },
      primary_verdict: "tradeoff",
      promotion_decision: "do_not_promote",
      seed_count: 1,
      story_note: "Worst-group improved on the scout, but OOD, ID, and calibration regressed enough to stop.",
    },
  ],
  worst_group_summary: [
    {
      comparison_mode: "baseline_metric",
      display_name: "DistilBERT Baseline",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "distilbert_baseline",
      mean: 0.306,
      std: 0.007,
      primary_verdict: "stable",
      seed_count: 3,
      story_note: "Stable reference baseline showing the benchmark robustness gap under shift.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Temperature Scaling",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "temperature_scaling",
      mean: 0,
      std: 0,
      primary_verdict: "stable",
      seed_count: 3,
      story_note: "Stable calibration reference lane with no meaningful robustness upside.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Reweighting",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "reweighting",
      mean: 0.06,
      std: 0.008,
      primary_verdict: "mixed",
      seed_count: 3,
      story_note: "Best current robustness lane, but the official seeded story remains mixed.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Group DRO",
      evidence_scope: "exploratory_scout",
      is_exploratory: true,
      method_name: "group_dro",
      mean: -0.215,
      std: null,
      primary_verdict: "failure",
      promotion_decision: "do_not_promote",
      seed_count: 1,
      story_note: "Scout failure against the parent baseline; not worth promotion.",
    },
  ],
  ood_summary: [
    {
      comparison_mode: "baseline_metric",
      display_name: "DistilBERT Baseline",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "distilbert_baseline",
      mean: 0.8,
      std: 0.001,
      primary_verdict: "stable",
      seed_count: 3,
      story_note: "Stable reference baseline showing the benchmark robustness gap under shift.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Temperature Scaling",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "temperature_scaling",
      mean: 0,
      std: 0,
      primary_verdict: "stable",
      seed_count: 3,
      story_note: "Stable calibration reference lane with no meaningful robustness upside.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Reweighting",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "reweighting",
      mean: 0.001,
      std: 0.001,
      primary_verdict: "mixed",
      seed_count: 3,
      story_note: "Best current robustness lane, but the official seeded story remains mixed.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Group-Balanced Sampling",
      evidence_scope: "exploratory_scout",
      is_exploratory: true,
      method_name: "group_balanced_sampling",
      mean: -0.096,
      std: null,
      primary_verdict: "tradeoff",
      promotion_decision: "do_not_promote",
      seed_count: 1,
      story_note: "Worst-group improved on the scout, but OOD, ID, and calibration regressed enough to stop.",
    },
  ],
  id_summary: [
    {
      comparison_mode: "baseline_metric",
      display_name: "DistilBERT Baseline",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "distilbert_baseline",
      mean: 0.87,
      std: 0.0003,
      primary_verdict: "stable",
      seed_count: 3,
      story_note: "Stable reference baseline showing the benchmark robustness gap under shift.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Temperature Scaling",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "temperature_scaling",
      mean: 0,
      std: 0,
      primary_verdict: "stable",
      seed_count: 3,
      story_note: "Stable calibration reference lane with no meaningful robustness upside.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Reweighting",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "reweighting",
      mean: -0.011,
      std: 0.002,
      primary_verdict: "mixed",
      seed_count: 3,
      story_note: "Best current robustness lane, but the official seeded story remains mixed.",
    },
  ],
  calibration_summary: [
    {
      comparison_mode: "baseline_metric",
      display_name: "DistilBERT Baseline",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "distilbert_baseline",
      ece_mean: 0.023,
      ece_std: 0.001,
      brier_score_mean: 0.046,
      brier_score_std: 0.0001,
      primary_verdict: "stable",
      seed_count: 3,
      story_note: "Stable reference baseline showing the benchmark robustness gap under shift.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Temperature Scaling",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "temperature_scaling",
      ece_mean: -0.011,
      ece_std: 0.001,
      brier_score_mean: -0.001,
      brier_score_std: 0.0001,
      primary_verdict: "stable",
      seed_count: 3,
      story_note: "Stable calibration reference lane with no meaningful robustness upside.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Reweighting",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "reweighting",
      ece_mean: 0.006,
      ece_std: 0.001,
      brier_score_mean: 0.007,
      brier_score_std: 0.001,
      primary_verdict: "mixed",
      seed_count: 3,
      story_note: "Best current robustness lane, but the official seeded story remains mixed.",
    },
    {
      comparison_mode: "delta_vs_baseline",
      display_name: "Group DRO",
      evidence_scope: "exploratory_scout",
      is_exploratory: true,
      method_name: "group_dro",
      ece_mean: 0.033,
      ece_std: null,
      brier_score_mean: 0.026,
      brier_score_std: null,
      primary_verdict: "failure",
      promotion_decision: "do_not_promote",
      seed_count: 1,
      story_note: "Scout failure against the parent baseline; not worth promotion.",
    },
  ],
  final_robustness_verdict: "still_mixed",
  promotion_audit: {
    audit_name: "phase25_group_balanced_sampling",
    candidate_display_name: "Group-Balanced Sampling",
    candidate_method: "group_balanced_sampling",
    decision: "do_not_promote",
    decision_reason:
      "Worst-group F1 improved on the scout, but ID Macro F1, OOD Macro F1, ECE, and Brier all regressed materially.",
    reference_method: "reweighting",
    reference_stability_label: "mixed",
  },
};

const FINAL_REPORT_SUMMARY: FinalRobustnessReportSummary = {
  final_robustness_verdict: "still_mixed",
  headline_findings: [
    "Temperature scaling remains the stable calibration lane.",
    "Reweighting is still the best current robustness lane, but it remains mixed.",
  ],
  key_takeaway:
    "Calibration is solved more cleanly than robustness in the current benchmark.",
  next_step: "Keep the second-dataset gate deferred until robustness stops being mixed.",
  official_methods: [
    {
      comparison_mode: "baseline_metric",
      display_name: "DistilBERT Baseline",
      evidence_scope: "official_seeded",
      is_exploratory: false,
      method_name: "distilbert_baseline",
      metrics: {
        mean: {
          worst_group_f1: 0.306,
          ood_macro_f1: 0.8,
          id_macro_f1: 0.87,
          ece: 0.023,
          brier_score: 0.046,
        },
        std: {
          worst_group_f1: 0.007,
          ood_macro_f1: 0.001,
          id_macro_f1: 0.0003,
          ece: 0.001,
          brier_score: 0.0001,
        },
      },
      primary_verdict: "stable",
      seed_count: 3,
      stability_label: "stable",
      story_note: "Stable reference baseline showing the benchmark robustness gap under shift.",
    },
    ...FINAL_REPORT_DATA.official_method_summaries,
  ],
  exploratory_methods: FINAL_REPORT_DATA.exploratory_method_summaries,
};

function buildRunArtifactRefs(runId: string) {
  return {
    metrics_json: { path: `artifacts/runs/${runId}/metrics.json`, exists: true },
    selected_checkpoint: {
      path: `artifacts/runs/${runId}/checkpoint/best_model.pt`,
      exists: true,
    },
    training_history_json: {
      path: `artifacts/runs/${runId}/checkpoint/training_history.json`,
      exists: true,
    },
    predictions: {
      id_test: { path: `artifacts/runs/${runId}/predictions_id_test.parquet`, exists: true },
      ood_test: { path: `artifacts/runs/${runId}/predictions_ood_test.parquet`, exists: true },
      validation: { path: `artifacts/runs/${runId}/predictions_val.parquet`, exists: true },
    },
  };
}

function buildEvaluationArtifactRefs(evalId: string) {
  return {
    overall_metrics_json: { path: `artifacts/evals/${evalId}/overall_metrics.json`, exists: true },
    id_ood_comparison_csv: {
      path: `artifacts/evals/${evalId}/id_ood_comparison.csv`,
      exists: true,
    },
    split_metrics_csv: { path: `artifacts/evals/${evalId}/split_metrics.csv`, exists: true },
    subgroup_metrics_csv: {
      path: `artifacts/evals/${evalId}/subgroup_metrics.csv`,
      exists: true,
    },
  };
}

const RUNS: RunEntity[] = [
  {
    id: "baseline_seed_13",
    run_id: "baseline_seed_13",
    entity_type: "run",
    default_visible: true,
    is_official: true,
    experiment_type: "baseline",
    model_name: "distilbert",
    seed: "13",
    status: "completed",
    experiment_group: "baselines_v1_2_distilbert",
    metadata_path: "artifacts/runs/baseline_seed_13/metadata.json",
    notes: "Official DistilBERT baseline seed.",
    artifact_refs: buildRunArtifactRefs("baseline_seed_13"),
    tags: ["official", "baseline", "seed_13"],
  },
  {
    id: "baseline_seed_42",
    run_id: "baseline_seed_42",
    entity_type: "run",
    default_visible: true,
    is_official: true,
    experiment_type: "baseline",
    model_name: "distilbert",
    seed: "42",
    status: "completed",
    experiment_group: "baselines_v1_2_distilbert",
    metadata_path: "artifacts/runs/baseline_seed_42/metadata.json",
    notes: "Official DistilBERT baseline seed.",
    artifact_refs: buildRunArtifactRefs("baseline_seed_42"),
    tags: ["official", "baseline", "seed_42"],
  },
  {
    id: "baseline_seed_87",
    run_id: "baseline_seed_87",
    entity_type: "run",
    default_visible: true,
    is_official: true,
    experiment_type: "baseline",
    model_name: "distilbert",
    seed: "87",
    status: "completed",
    experiment_group: "baselines_v1_2_distilbert",
    metadata_path: "artifacts/runs/baseline_seed_87/metadata.json",
    notes: "Official DistilBERT baseline seed.",
    artifact_refs: buildRunArtifactRefs("baseline_seed_87"),
    tags: ["official", "baseline", "seed_87"],
  },
  {
    id: "temperature_seed_13",
    run_id: "temperature_seed_13",
    entity_type: "run",
    default_visible: true,
    is_official: true,
    experiment_type: "mitigation",
    mitigation_method: "temperature_scaling",
    model_name: "distilbert",
    parent_run_id: "baseline_seed_13",
    seed: "13",
    status: "completed",
    experiment_group: "temperature_scaling_v1_2",
    metadata_path: "artifacts/runs/temperature_seed_13/metadata.json",
    notes: "Official calibration lane seed.",
    artifact_refs: buildRunArtifactRefs("temperature_seed_13"),
    tags: ["official", "temperature_scaling", "seed_13"],
  },
  {
    id: "temperature_seed_42",
    run_id: "temperature_seed_42",
    entity_type: "run",
    default_visible: true,
    is_official: true,
    experiment_type: "mitigation",
    mitigation_method: "temperature_scaling",
    model_name: "distilbert",
    parent_run_id: "baseline_seed_42",
    seed: "42",
    status: "completed",
    experiment_group: "temperature_scaling_v1_2",
    metadata_path: "artifacts/runs/temperature_seed_42/metadata.json",
    notes: "Official calibration lane seed.",
    artifact_refs: buildRunArtifactRefs("temperature_seed_42"),
    tags: ["official", "temperature_scaling", "seed_42"],
  },
  {
    id: "temperature_seed_87",
    run_id: "temperature_seed_87",
    entity_type: "run",
    default_visible: true,
    is_official: true,
    experiment_type: "mitigation",
    mitigation_method: "temperature_scaling",
    model_name: "distilbert",
    parent_run_id: "baseline_seed_87",
    seed: "87",
    status: "completed",
    experiment_group: "temperature_scaling_v1_2",
    metadata_path: "artifacts/runs/temperature_seed_87/metadata.json",
    notes: "Official calibration lane seed.",
    artifact_refs: buildRunArtifactRefs("temperature_seed_87"),
    tags: ["official", "temperature_scaling", "seed_87"],
  },
  {
    id: "reweighting_seed_13",
    run_id: "reweighting_seed_13",
    entity_type: "run",
    default_visible: true,
    is_official: true,
    experiment_type: "mitigation",
    mitigation_method: "reweighting",
    model_name: "distilbert",
    parent_run_id: "baseline_seed_13",
    seed: "13",
    status: "completed",
    experiment_group: "reweighting_v1_3",
    metadata_path: "artifacts/runs/reweighting_seed_13/metadata.json",
    notes: "Best current robustness lane, still mixed.",
    artifact_refs: buildRunArtifactRefs("reweighting_seed_13"),
    tags: ["official", "reweighting", "seed_13"],
  },
  {
    id: "reweighting_seed_42",
    run_id: "reweighting_seed_42",
    entity_type: "run",
    default_visible: true,
    is_official: true,
    experiment_type: "mitigation",
    mitigation_method: "reweighting",
    model_name: "distilbert",
    parent_run_id: "baseline_seed_42",
    seed: "42",
    status: "completed",
    experiment_group: "reweighting_v1_3",
    metadata_path: "artifacts/runs/reweighting_seed_42/metadata.json",
    notes: "Best current robustness lane, still mixed.",
    artifact_refs: buildRunArtifactRefs("reweighting_seed_42"),
    tags: ["official", "reweighting", "seed_42"],
  },
  {
    id: "reweighting_seed_87",
    run_id: "reweighting_seed_87",
    entity_type: "run",
    default_visible: true,
    is_official: true,
    experiment_type: "mitigation",
    mitigation_method: "reweighting",
    model_name: "distilbert",
    parent_run_id: "baseline_seed_87",
    seed: "87",
    status: "completed",
    experiment_group: "reweighting_v1_3",
    metadata_path: "artifacts/runs/reweighting_seed_87/metadata.json",
    notes: "Best current robustness lane, still mixed.",
    artifact_refs: buildRunArtifactRefs("reweighting_seed_87"),
    tags: ["official", "reweighting", "seed_87"],
  },
  {
    id: "group_dro_seed_13",
    run_id: "group_dro_seed_13",
    entity_type: "run",
    default_visible: false,
    is_official: false,
    experiment_type: "mitigation",
    mitigation_method: "group_dro",
    model_name: "distilbert",
    parent_run_id: "baseline_seed_13",
    seed: "13",
    status: "completed",
    experiment_group: "group_dro_v1_3",
    metadata_path: "artifacts/runs/group_dro_seed_13/metadata.json",
    notes: "Scout failure against the parent baseline.",
    artifact_refs: buildRunArtifactRefs("group_dro_seed_13"),
    tags: ["exploratory", "group_dro", "scout", "seed_13"],
  },
  {
    id: "group_balanced_sampling_seed_13",
    run_id: "group_balanced_sampling_seed_13",
    entity_type: "run",
    default_visible: false,
    is_official: false,
    experiment_type: "mitigation",
    mitigation_method: "group_balanced_sampling",
    model_name: "distilbert",
    parent_run_id: "baseline_seed_13",
    seed: "13",
    status: "completed",
    experiment_group: "group_balanced_sampling_v1_4",
    metadata_path: "artifacts/runs/group_balanced_sampling_seed_13/metadata.json",
    notes: "Scout tradeoff lane with stronger worst-group but weaker overall reliability.",
    artifact_refs: buildRunArtifactRefs("group_balanced_sampling_seed_13"),
    tags: ["exploratory", "group_balanced_sampling", "scout", "seed_13"],
  },
];

const EVALUATIONS: EvaluationEntity[] = [
  {
    id: "eval_baseline_13",
    eval_id: "eval_baseline_13",
    entity_type: "evaluation",
    default_visible: true,
    is_official: true,
    source_run_id: "baseline_seed_13",
    seed: "13",
    metadata_path: "artifacts/evals/eval_baseline_13/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_baseline_13"),
    payload_refs: buildEvaluationArtifactRefs("eval_baseline_13"),
    headline_metrics: {
      macro_f1: 0.842,
      worst_group_f1: 0.316,
    },
  },
  {
    id: "eval_baseline_42",
    eval_id: "eval_baseline_42",
    entity_type: "evaluation",
    default_visible: true,
    is_official: true,
    source_run_id: "baseline_seed_42",
    seed: "42",
    metadata_path: "artifacts/evals/eval_baseline_42/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_baseline_42"),
    payload_refs: buildEvaluationArtifactRefs("eval_baseline_42"),
    headline_metrics: {
      macro_f1: 0.842,
      worst_group_f1: 0.301,
    },
  },
  {
    id: "eval_baseline_87",
    eval_id: "eval_baseline_87",
    entity_type: "evaluation",
    default_visible: true,
    is_official: true,
    source_run_id: "baseline_seed_87",
    seed: "87",
    metadata_path: "artifacts/evals/eval_baseline_87/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_baseline_87"),
    payload_refs: buildEvaluationArtifactRefs("eval_baseline_87"),
    headline_metrics: {
      macro_f1: 0.843,
      worst_group_f1: 0.301,
    },
  },
  {
    id: "eval_temperature_13",
    eval_id: "eval_temperature_13",
    entity_type: "evaluation",
    default_visible: true,
    is_official: true,
    source_run_id: "temperature_seed_13",
    seed: "13",
    metadata_path: "artifacts/evals/eval_temperature_13/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_temperature_13"),
    payload_refs: buildEvaluationArtifactRefs("eval_temperature_13"),
    headline_metrics: {
      macro_f1: 0.842,
      worst_group_f1: 0.316,
    },
  },
  {
    id: "eval_temperature_42",
    eval_id: "eval_temperature_42",
    entity_type: "evaluation",
    default_visible: true,
    is_official: true,
    source_run_id: "temperature_seed_42",
    seed: "42",
    metadata_path: "artifacts/evals/eval_temperature_42/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_temperature_42"),
    payload_refs: buildEvaluationArtifactRefs("eval_temperature_42"),
    headline_metrics: {
      macro_f1: 0.842,
      worst_group_f1: 0.301,
    },
  },
  {
    id: "eval_temperature_87",
    eval_id: "eval_temperature_87",
    entity_type: "evaluation",
    default_visible: true,
    is_official: true,
    source_run_id: "temperature_seed_87",
    seed: "87",
    metadata_path: "artifacts/evals/eval_temperature_87/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_temperature_87"),
    payload_refs: buildEvaluationArtifactRefs("eval_temperature_87"),
    headline_metrics: {
      macro_f1: 0.843,
      worst_group_f1: 0.301,
    },
  },
  {
    id: "eval_reweighting_13",
    eval_id: "eval_reweighting_13",
    entity_type: "evaluation",
    default_visible: true,
    is_official: true,
    source_run_id: "reweighting_seed_13",
    seed: "13",
    metadata_path: "artifacts/evals/eval_reweighting_13/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_reweighting_13"),
    payload_refs: buildEvaluationArtifactRefs("eval_reweighting_13"),
    headline_metrics: {
      macro_f1: 0.834,
      worst_group_f1: 0.377,
    },
  },
  {
    id: "eval_reweighting_42",
    eval_id: "eval_reweighting_42",
    entity_type: "evaluation",
    default_visible: true,
    is_official: true,
    source_run_id: "reweighting_seed_42",
    seed: "42",
    metadata_path: "artifacts/evals/eval_reweighting_42/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_reweighting_42"),
    payload_refs: buildEvaluationArtifactRefs("eval_reweighting_42"),
    headline_metrics: {
      macro_f1: 0.831,
      worst_group_f1: 0.361,
    },
  },
  {
    id: "eval_reweighting_87",
    eval_id: "eval_reweighting_87",
    entity_type: "evaluation",
    default_visible: true,
    is_official: true,
    source_run_id: "reweighting_seed_87",
    seed: "87",
    metadata_path: "artifacts/evals/eval_reweighting_87/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_reweighting_87"),
    payload_refs: buildEvaluationArtifactRefs("eval_reweighting_87"),
    headline_metrics: {
      macro_f1: 0.832,
      worst_group_f1: 0.359,
    },
  },
  {
    id: "eval_group_dro_13",
    eval_id: "eval_group_dro_13",
    entity_type: "evaluation",
    default_visible: false,
    is_official: false,
    source_run_id: "group_dro_seed_13",
    seed: "13",
    metadata_path: "artifacts/evals/eval_group_dro_13/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_group_dro_13"),
    payload_refs: buildEvaluationArtifactRefs("eval_group_dro_13"),
    headline_metrics: {
      macro_f1: 0.756,
      worst_group_f1: 0.091,
    },
  },
  {
    id: "eval_group_balanced_sampling_13",
    eval_id: "eval_group_balanced_sampling_13",
    entity_type: "evaluation",
    default_visible: false,
    is_official: false,
    source_run_id: "group_balanced_sampling_seed_13",
    seed: "13",
    metadata_path: "artifacts/evals/eval_group_balanced_sampling_13/metadata.json",
    artifact_refs: buildEvaluationArtifactRefs("eval_group_balanced_sampling_13"),
    payload_refs: buildEvaluationArtifactRefs("eval_group_balanced_sampling_13"),
    headline_metrics: {
      macro_f1: 0.724,
      worst_group_f1: 0.459,
    },
  },
];

export function buildManifestFixture(): ArtifactIndex {
  return {
    schema_version: "artifact_index_v1",
    default_filters: { official_only: true },
    entities: {
      runs: RUNS,
      evaluations: EVALUATIONS,
      reports: [FINAL_REPORT, TEMPERATURE_REPORT, REWEIGHTING_REPORT],
    },
    views: {
      seeded_cohorts: [
        {
          cohort_id: "distilbert_baseline",
          display_name: "DistilBERT Baseline",
          cohort_type: "baseline",
          model_name: "distilbert",
          default_visible: true,
          is_official: true,
          aggregate_metrics: {
            mean: { id_macro_f1: 0.842, worst_group_f1: 0.306 },
            std: { id_macro_f1: 0.0003, worst_group_f1: 0.007 },
          },
          per_seed_metrics: [
            {
              seed: "13",
              run_id: "baseline_seed_13",
              eval_id: "eval_baseline_13",
              id_macro_f1: 0.842,
              worst_group_f1: 0.316,
              ood_macro_f1: 0.801,
              ece: 0.023,
              brier_score: 0.046,
            },
            {
              seed: "42",
              run_id: "baseline_seed_42",
              eval_id: "eval_baseline_42",
              id_macro_f1: 0.842,
              worst_group_f1: 0.301,
              ood_macro_f1: 0.8,
              ece: 0.024,
              brier_score: 0.046,
            },
            {
              seed: "87",
              run_id: "baseline_seed_87",
              eval_id: "eval_baseline_87",
              id_macro_f1: 0.843,
              worst_group_f1: 0.301,
              ood_macro_f1: 0.799,
              ece: 0.022,
              brier_score: 0.046,
            },
          ],
        },
        {
          cohort_id: "temperature_scaling",
          display_name: "Temperature Scaling",
          cohort_type: "mitigation",
          model_name: "distilbert",
          mitigation_method: "temperature_scaling",
          default_visible: true,
          is_official: true,
          aggregate_metrics: {
            mean: { id_macro_f1: 0.842, worst_group_f1: 0.306 },
            std: { id_macro_f1: 0.0003, worst_group_f1: 0.007 },
          },
          per_seed_metrics: [
            {
              seed: "13",
              run_id: "temperature_seed_13",
              eval_id: "eval_temperature_13",
              id_macro_f1: 0.842,
              worst_group_f1: 0.316,
              ood_macro_f1: 0.801,
              ece: 0.012,
              brier_score: 0.045,
            },
            {
              seed: "42",
              run_id: "temperature_seed_42",
              eval_id: "eval_temperature_42",
              id_macro_f1: 0.842,
              worst_group_f1: 0.301,
              ood_macro_f1: 0.8,
              ece: 0.013,
              brier_score: 0.045,
            },
            {
              seed: "87",
              run_id: "temperature_seed_87",
              eval_id: "eval_temperature_87",
              id_macro_f1: 0.843,
              worst_group_f1: 0.301,
              ood_macro_f1: 0.799,
              ece: 0.011,
              brier_score: 0.045,
            },
          ],
        },
        {
          cohort_id: "reweighting",
          display_name: "Reweighting",
          cohort_type: "mitigation",
          model_name: "distilbert",
          mitigation_method: "reweighting",
          default_visible: true,
          is_official: true,
          aggregate_metrics: {
            mean: { id_macro_f1: 0.832, worst_group_f1: 0.366 },
            std: { id_macro_f1: 0.002, worst_group_f1: 0.008 },
          },
          per_seed_metrics: [
            {
              seed: "13",
              run_id: "reweighting_seed_13",
              eval_id: "eval_reweighting_13",
              id_macro_f1: 0.834,
              worst_group_f1: 0.377,
              ood_macro_f1: 0.801,
              ece: 0.029,
              brier_score: 0.054,
            },
            {
              seed: "42",
              run_id: "reweighting_seed_42",
              eval_id: "eval_reweighting_42",
              id_macro_f1: 0.831,
              worst_group_f1: 0.361,
              ood_macro_f1: 0.801,
              ece: 0.029,
              brier_score: 0.053,
            },
            {
              seed: "87",
              run_id: "reweighting_seed_87",
              eval_id: "eval_reweighting_87",
              id_macro_f1: 0.832,
              worst_group_f1: 0.359,
              ood_macro_f1: 0.8,
              ece: 0.028,
              brier_score: 0.053,
            },
          ],
        },
      ],
      mitigation_comparisons: [
        {
          view_id: "temperature_scaling_view",
          mitigation_method: "temperature_scaling",
          default_visible: true,
          is_official: true,
          aggregate_report_id: TEMPERATURE_REPORT.id,
          stability_assessment: { label: "stable" },
          comparison_summary: {
            report_id: TEMPERATURE_REPORT.id,
            report_markdown: TEMPERATURE_REPORT.artifact_refs?.report_markdown,
          },
          per_seed_comparisons: [
            {
              seed: "13",
              child_run_id: "temperature_seed_13",
              child_eval_id: "eval_temperature_13",
              verdict: "win",
              deltas: {
                worst_group_f1_delta: 0,
                ood_macro_f1_delta: 0,
                id_macro_f1_delta: 0,
                ece_delta: -0.011,
                brier_score_delta: -0.001,
              },
            },
            {
              seed: "42",
              child_run_id: "temperature_seed_42",
              child_eval_id: "eval_temperature_42",
              verdict: "win",
              deltas: {
                worst_group_f1_delta: 0,
                ood_macro_f1_delta: 0,
                id_macro_f1_delta: 0,
                ece_delta: -0.011,
                brier_score_delta: -0.001,
              },
            },
            {
              seed: "87",
              child_run_id: "temperature_seed_87",
              child_eval_id: "eval_temperature_87",
              verdict: "win",
              deltas: {
                worst_group_f1_delta: 0,
                ood_macro_f1_delta: 0,
                id_macro_f1_delta: 0,
                ece_delta: -0.011,
                brier_score_delta: -0.001,
              },
            },
          ],
        },
        {
          view_id: "reweighting_view",
          mitigation_method: "reweighting",
          default_visible: true,
          is_official: true,
          aggregate_report_id: REWEIGHTING_REPORT.id,
          stability_assessment: { label: "mixed" },
          comparison_summary: {
            report_id: REWEIGHTING_REPORT.id,
            report_markdown: REWEIGHTING_REPORT.artifact_refs?.report_markdown,
          },
          per_seed_comparisons: [
            {
              seed: "13",
              child_run_id: "reweighting_seed_13",
              child_eval_id: "eval_reweighting_13",
              verdict: "tradeoff",
              deltas: {
                worst_group_f1_delta: 0.062,
                ood_macro_f1_delta: 0,
                id_macro_f1_delta: -0.013,
                ece_delta: 0.007,
                brier_score_delta: 0.008,
              },
            },
            {
              seed: "42",
              child_run_id: "reweighting_seed_42",
              child_eval_id: "eval_reweighting_42",
              verdict: "tradeoff",
              deltas: {
                worst_group_f1_delta: 0.055,
                ood_macro_f1_delta: 0.001,
                id_macro_f1_delta: -0.011,
                ece_delta: 0.005,
                brier_score_delta: 0.007,
              },
            },
            {
              seed: "87",
              child_run_id: "reweighting_seed_87",
              child_eval_id: "eval_reweighting_87",
              verdict: "tradeoff",
              deltas: {
                worst_group_f1_delta: 0.053,
                ood_macro_f1_delta: 0.002,
                id_macro_f1_delta: -0.01,
                ece_delta: 0.006,
                brier_score_delta: 0.006,
              },
            },
          ],
        },
      ],
      stability_packages: [
        {
          view_id: "phase20_stability",
          default_visible: true,
          is_official: true,
          milestone_assessment: {
            dataset_expansion_recommendation: "defer_now_reopen_under_conditions",
            recommendation_reason: "Robustness remains mixed.",
            next_step: "Hold dataset expansion until robustness stabilizes.",
          },
        },
      ],
      research_closeout: [
        {
          view_id: "phase27_gate",
          default_visible: true,
          is_official: true,
          final_robustness_verdict: "still_mixed",
          dataset_expansion_decision: "defer_now_reopen_under_conditions",
          recommendation_reason:
            "Calibration is solved more cleanly than robustness, so the gate stays closed.",
          official_methods: ["temperature_scaling", "reweighting"],
          exploratory_methods: ["group_dro", "group_balanced_sampling"],
          summary_bullets: [
            "The baseline robustness gap remains real and stable.",
            "Temperature scaling remains the stable calibration lane.",
          ],
          reopen_conditions: [
            "Robustness lane achieves stable improvement instead of remaining mixed.",
          ],
        },
      ],
    },
  };
}

export function buildFinalRobustnessBundleFixture(): FinalRobustnessBundle {
  return {
    report: FINAL_REPORT,
    data: FINAL_REPORT_DATA,
    summary: FINAL_REPORT_SUMMARY,
  };
}
