/**
 * The console's validators must accept what `scripts/query_bridge.py` actually emits.
 *
 * Every other test in this suite feeds the validators fixtures from `src/test/factories.ts`,
 * which is explicitly written to follow "what each validator actually reads". That makes the
 * contract circular: the reader is tested against a mirror of itself, so a Python producer
 * that renames or drops a field leaves every test green. That is exactly how the `gate`
 * endpoint shipped without `policy_source` / `waiver_source` while the gate screen claimed
 * "built-in defaults / waivers: none" over a committed governance/policy.yml.
 *
 * `tests/fixtures/bridge/*.json` is real bridge output, committed and regenerated by
 * `tests/unit/test_bridge_payload_contract.py`. Reading it here closes the loop: the Python
 * test proves the producer still emits those bytes, and this one proves the consumer
 * accepts them. No Python runtime is needed at vitest time -- the fixtures are the contract.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  validateBaselinesResponse,
  validateDatasetDraftsResponse,
  validateDatasetFamiliesResponse,
  validateGateResponse,
  validateHistorySnapshotResponse,
} from "@/lib/artifacts/extended";
import {
  validateArtifactDatasetVersions,
  validateComparisonInventory,
  validateRunInventory,
} from "@/lib/artifacts/load";

const FIXTURE_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../../../tests/fixtures/bridge",
);

function readGolden(name: string): unknown {
  return JSON.parse(readFileSync(path.join(FIXTURE_DIR, `${name}.json`), "utf-8"));
}

/**
 * `runs` and `comparisons` are the two endpoints where the vite middleware supplies the
 * envelope itself (`{ source, runs }` / `{ source, comparisons }`) and the bridge supplies
 * only the row array. The rows are where drift happens and where the golden file earns its
 * keep, so those two goldens are wrapped in the middleware's envelope here. The envelope is
 * asserted separately by the page-level tests, which drive the real loaders.
 */
const SOURCE_ENVELOPE = {
  label: "Configured artifact store",
  path: "{WORKSPACE}",
  runsPath: "{WORKSPACE}/runs",
  reportsPath: "{WORKSPACE}/reports",
};

const CONTRACTS: Array<{ name: string; validate: (payload: unknown) => unknown }> = [
  {
    name: "runs",
    validate: (rows) => validateRunInventory({ source: SOURCE_ENVELOPE, runs: rows }),
  },
  {
    name: "comparisons",
    validate: (rows) =>
      validateComparisonInventory({ source: SOURCE_ENVELOPE, comparisons: rows }),
  },
  { name: "gate", validate: validateGateResponse },
  { name: "dataset-families", validate: validateDatasetFamiliesResponse },
  { name: "dataset-drafts", validate: validateDatasetDraftsResponse },
  { name: "baselines", validate: validateBaselinesResponse },
  { name: "dataset-versions", validate: validateArtifactDatasetVersions },
  { name: "history", validate: validateHistorySnapshotResponse },
];

describe("bridge payload contract", () => {
  it.each(CONTRACTS)("accepts real $name output from query_bridge.py", ({ name, validate }) => {
    expect(() => validate(readGolden(name))).not.toThrow();
  });

  it("supplies the counts the overview envelope is composed from", () => {
    // `overview.json` is the one endpoint with no 1:1 validator: the middleware composes
    // its response from three bridge calls, so `validateArtifactOverview` sees a shape the
    // bridge never emits alone. Pin the counts the middleware reads instead.
    const overview = readGolden("overview") as Record<string, unknown>;
    for (const key of ["run_count", "comparison_count", "case_count", "delta_count"]) {
      expect(typeof overview[key], `overview.${key}`).toBe("number");
    }
  });

  it("carries the policy and waiver provenance the gate screen renders", () => {
    const gate = validateGateResponse(readGolden("gate"));
    // Not just "present" -- the screen prints these verbatim, so a fabricated default is
    // indistinguishable from a real answer to the reader.
    expect(gate.policySource).toBeTruthy();
    expect(gate.waiverSource).not.toBeUndefined();
    expect(gate.rows.length).toBeGreaterThan(0);
    for (const row of gate.rows) {
      expect(row.blockReason).not.toBeUndefined();
      // A blocked decision must be able to say why; that string is what CI printed.
      if (row.blocked) {
        expect(row.blockReason).toBeTruthy();
      }
    }
  });

  it("rejects a gate payload that drops the policy provenance", () => {
    const gate = readGolden("gate") as Record<string, unknown>;
    const { policy_source: _omitted, ...withoutPolicySource } = gate;
    expect(() => validateGateResponse(withoutPolicySource)).toThrow(
      /gate\.policy_source is required/,
    );

    const { waiver_source: _alsoOmitted, ...withoutWaiverSource } = gate;
    expect(() => validateGateResponse(withoutWaiverSource)).toThrow(
      /gate\.waiver_source is required/,
    );
  });

  it("keeps draft provenance non-null so the Datasets screen can show where a draft came from", () => {
    const drafts = validateDatasetDraftsResponse(readGolden("dataset-drafts"));
    expect(drafts.drafts.length).toBeGreaterThan(0);
    for (const draft of drafts.drafts) {
      // A CLI-harvested draft used to arrive with a null comparison id and origin, so the
      // source column rendered blank while console-created drafts showed both.
      expect(draft.comparisonReportId ?? draft.runId).toBeTruthy();
    }
  });
});
